# Dockerfile

FROM python:3.9-slim

WORKDIR /app

COPY app /app
COPY model.onnx /app/model.onnx

RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

ENV CEREBRIUM=1

CMD ["python3"]
